const AppActions = {
    LOGIN_SUCCESS: "login_success",
    LOGIN_FAILURE: "login_failure",
    SIGNUP_SUCCESS: "signup_success",
    SIGNUP_FAILURE: "signup_failure",
    USER_PROFILE_FETCH: "user_profile_fetch",
    USER_PROFILE_FETCH_SUCCESS: "user_profile_fetch_success",
    USER_PROFILE_FETCH_FAILURE: "user_profile_fetch_failure",
    USER_PROFILE_UPDATE_SUCCESS: "user_profie_update_sucess",
    USER_PROFILE_UPDATE_FAILURE: "user_profie_update_failure",
    USER_PROFILE_UPDATE: "user_profie_update",
    USER_PROFILE_PICTURE_UPLOAD_SUCCESS: "user_profie_picture_upload_sucess",
    USER_PROFILE_PICTURE_UPLOAD_FAILURE: "user_profie_picture_upload_failure",
    POST_PROPERTY_INPUT_CHANGE: "post_property_input_change",
    POST_PROPERTY_UPLOAD_PICTURE_SUCCESS: "post_property_upload_picture_success",
    POST_PROPERTY_UPLOAD_PICTURE_FAILURE: "post_property_upload_picture_failure",
    POST_PROPERTY_SUCCESS: "post_property_success",
    POST_PROPERTY_FAILURE: "post_property_failure",
    LOGOUT_REDUX_RESET : "logout_redux_reset",
    SEARCH_PROPERTY_SUCCESS : "search_property_success",
    SEARCH_PROPERTY_FAILURE : "search_property_failure",
    SEARCH_PROPERTY_INPUT_CHANGE : "search_property_input_change",
    VIEW_PROPERTY_DETAIL:"view_property_detail",
    BOOK_PROPERTY_SUCCESS:"book_property_success",
    BOOK_PROPERTY_FAILURE:"book_property_failure",
    BOOKING_HISTORY_SUCCESS:"booking_history_success",
    BOOKING_HISTORY_FAILURE:"booking_history_failure",
    ASK_QUESTION_SUCCESS:"ask_question_success",
    ASK_QUESTION_FAILURE:"ask_question_failure",
    VIEW_CONVERSATION:"view_conversation",
    SEND_MESSAGE:"send_message",
    FETCH_CONVERSATIONS_SUCCESS:"fetch_conversations_success",
    FETCH_CONVERSATIONS_FAILURE:"fetch_conversations_failure",
    POST_MESSAGE_SUCCESS:"post_message_success",
    POST_MESSAGE_FAILURE:"post_message_failure"
}
export default AppActions;