const AppActions = {
    LOGIN_SUCCESS: "login_success",
    LOGIN_FAILURE: "login_failure",
    SIGNUP_SUCCESS: "signup_success",
    SIGNUP_FAILURE: "signup_failure",
    USER_PROFILE_FETCH: "user_profile_fetch",
    USER_PROFILE_FETCH_SUCCESS: "user_profile_fetch_success",
    USER_PROFILE_FETCH_FAILURE: "user_profile_fetch_failure",
    USER_PROFILE_UPDATE_SUCCESS: "user_profie_update_sucess",
    USER_PROFILE_UPDATE_FAILURE: "user_profie_update_failure",
    USER_PROFILE_UPDATE: "user_profie_update",
    USER_PROFILE_PICTURE_UPLOAD_SUCCESS: "user_profie_picture_upload_sucess",
    USER_PROFILE_PICTURE_UPLOAD_FAILURE: "user_profie_picture_upload_failure",
    POST_PROPERTY_INPUT_CHANGE: "post_property_input_change",
    POST_PROPERTY_UPLOAD_PICTURE_SUCCESS: "post_property_upload_picture_success",
    POST_PROPERTY_UPLOAD_PICTURE_FAILURE: "post_property_upload_picture_failure",
    POST_PROPERTY_SUCCESS: "post_property_success",
    POST_PROPERTY_FAILURE: "post_property_failure",
    LOGOUT_REDUX_RESET : "logout_redux_reset",
    SEARCH_PROPERTY_SUCCESS : "search_property_success",
    SEARCH_PROPERTY_FAILURE : "search_property_failure",
    SEARCH_PROPERTY_INPUT_CHANGE : "search_property_input_change",
}
export default AppActions;